services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
      POSTGRES_DB: tasksdb
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - .env
  worker:
    build: .
    restart: always
    command: node worker.js
    env_file:
      - .env
    depends_on:
      - db
volumes:
  pgdata: